services:
  postgres_db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: TodoList
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring_app:
    build: .
    container_name: springboot-service
    depends_on:
      - postgres_db
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/TodoList
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8000:8000"

volumes:
  postgres_data:
